name: Test Deploy

on:
  pull_request:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - '14'
        auto-deploy-repos:
          - lando/auto-deploy-action
    steps:
      - name: Checkout action code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: yarn
      - name: Test Deploy
        uses: ./
        with:
          # Required props
          slug: ${{ matrix.auto-deploy-repos }}
          manager: yarn

          # Optional props (defaults)
          token: ${{ github.token }}
          # @TOTO: some setting so we can get versoon/package from git
          package: lando
          version: 5
          # TOOD: support other managers
          # branch: main

          # Note: user is responsible for having correct tools and versions installed aka yarn on node14

          # Steps
          # step 3: deploy package (command is dynamic based on manager selection)
            # yarn install PACKAGE@VERSION
            # npm install PACKAGE@VERSION
          # step 4: add, commit, push
            # git add . git commit -m "autogenerated message" git push origin
          # step 5: optionally open PR
